---
# OU Structure
- name: Create ActiveDirectory OU Structure
  hosts: all
  gather_facts: false

  tasks:
    # service check
    - name: Set service startup mode to auto and ensure it is started
      ansible.windows.win_service:
        name: ADWS
        start_mode: auto
        state: started

    # Level 1 - parent container
    - name: Create Company OU
      community.windows.win_domain_ou:
        name: SavyLabs
        domain_username: savylabs\savy
        domain_password: Savy@123
        domain_server: sl-vm.savylabs.net
        path: "DC=savylabs,DC=net"
        state: present

    # Level 2 - Computers
    - name: Create Computers OU
      community.windows.win_domain_ou:
        name: Computers
        domain_username: savylabs\savy
        domain_password: Savy@123
        domain_server: sl-vm.savylabs.net
        path: "OU=SavyLabs,DC=savylabs,DC=net"
        state: present

    # Level 2 - Users
    - name: Create Users OU
      community.windows.win_domain_ou:
        name: Users
        domain_username: savylabs\savy
        domain_password: Savy@123
        domain_server: sl-vm.savylabs.net
        path: "OU=SavyLabs,DC=savylabs,DC=net"
        state: present

    # Level 2 - Groups
    - name: Create Groups OU
      community.windows.win_domain_ou:
        name: Groups
        domain_username: savylabs\savy
        domain_password: Savy@123
        domain_server: sl-vm.savylabs.net
        path: "OU=SavyLabs,DC=savylabs,DC=net"
        state: present

    # Level 3 - Laptops
    - name: Create Laptops OU
      community.windows.win_domain_ou:
        name: Laptops
        domain_username: savylabs\savy
        domain_password: Savy@123
        domain_server: sl-vm.savylabs.net
        path: "OU=Computers,OU=SavyLabs,DC=savylabs,DC=net"
        state: present

    # Level 3 - Desktops
    - name: Create Desktops OU
      community.windows.win_domain_ou:
        name: Desktops
        domain_username: savylabs\savy
        domain_password: Savy@123
        domain_server: sl-vm.savylabs.net
        path: "OU=Computers,OU=SavyLabs,DC=savylabs,DC=net"
        state: present

    # Level 3 - VDI
    - name: Create VDI OU
      community.windows.win_domain_ou:
        name: VDI
        domain_username: savylabs\savy
        domain_password: Savy@123
        domain_server: sl-vm.savylabs.net
        path: "OU=Computers,OU=SavyLabs,DC=savylabs,DC=net"
        state: present

# Groups
- name: Create Groups
  hosts: all
  gather_facts: false

  tasks:
    - name: Create Heroes Group
      community.windows.win_domain_group:
        name: Heroes
        display_name: Heroes
        scope: global
        category: security
        domain_username: savylabs\savy
        domain_password: Savy@123
        domain_server: sl-vm.savylabs.net
        organizational_unit: "OU=Groups,OU=SavyLabs,DC=savylabs,DC=net"
        state: present

    - name: Create Villains Group
      community.windows.win_domain_group:
        name: Villains
        display_name: Villains
        scope: global
        category: security
        domain_username: savylabs\savy
        domain_password: Savy@123
        domain_server: sl-vm.savylabs.net
        organizational_unit: "OU=Groups,OU=SavyLabs,DC=savylabs,DC=net"
        state: present

    - name: Create Marvel Comics Group
      community.windows.win_domain_group:
        name: Marvel Comics
        display_name: Marvel Comics
        scope: global
        category: security
        domain_username: savylabs\savy
        domain_password: Savy@123
        domain_server: sl-vm.savylabs.net
        organizational_unit: "OU=Groups,OU=SavyLabs,DC=savylabs,DC=net"
        state: present

    - name: Create DC Comics Group
      community.windows.win_domain_group:
        name: DC Comics
        display_name: DC Comics
        scope: global
        category: security
        domain_username: savylabs\savy
        domain_password: Savy@123
        domain_server: sl-vm.savylabs.net
        organizational_unit: "OU=Groups,OU=SavyLabs,DC=savylabs,DC=net"
        state: present

# Users
- name: Create User Accounts from CSV
  hosts: all
  gather_facts: false

  tasks:
    # read csv file users.csv
    - name: Read CSV file
      community.general.read_csv:
        path: users.csv
      delegate_to: localhost
      register: csv_results

    # debug to verify CSV data
    - name: Debug CSV data
      ansible.builtin.debug:
        msg: "{{ csv_results.list }}"
        # msg: 'First: {{ csv_results.list.1.first_name}} and Last: {{ csv_results.list.1.last_name }}'

    # debug to verify looping
    - name: Loop data
      ansible.builtin.debug:
        msg: 'First: {{ user.first_name}} and Last: {{ user.last_name }}'
      loop: "{{ csv_results.list }}"
      loop_control:
        loop_var: user

    # create users from csv data
    - name: Create User Accounts
      community.windows.win_domain_user:
        name: "{{ user.first_name }}"
        surname: "{{ user.last_name }}"
        sam_account_name: "{{ user.first_name }}.{{ user.last_name }}"
        display_name: "{{ user.first_name }}.{{ user.last_name }}"
        upn: "{{ user.first_name }}.{{ user.last_name }}@savylabs.net"
        password: Password123
        password_never_expires: true
        user_cannot_change_password: true
        enabled: true
        state: present
        path: "OU=Users,OU=SavyLabs,DC=savylabs,DC=net"
        domain_username: savylabs\savy
        domain_password: Savy@123
        domain_server: sl-vm.savylabs.net
      loop: "{{ csv_results.list }}"
      loop_control:
        loop_var: user