---
- name: Configure Windows Server as Domain Controller
  hosts: all

  tasks:
    - name: Install Active Directory Domain Services role
      ansible.windows.win_feature:
        name: AD-Domain-Services
        include_management_tools: true
        include_sub_features: true
        state: present

    - name: Create domain
      microsoft.ad.domain:
        dns_domain_name: savylabs.net
        install_dns: true
        create_dns_delegation: false
        safe_mode_password: Savy@123
        reboot: true